### PR TITLE
Evaluate: Hyacinth 51 revisited

### PR DESCRIPTION
**Pull request by barmintor**
I'll squash an resubmit if this looks okay.

### CODE REVIEW

**Comment by elo2112** [comment]
Still running into an issue when I try an export in that branch.  I just added a test in master that should verify that the feature is working (along with a couple of other changes/fixes).  Could you try a new pull request when you have a chance?

**Comment by elo2112** [comment]
Making a more thorough test now.  Will send another update soon.

**Comment by barmintor** [comment]
rebased to master, updated to include _digital_object_type.string_key and _project.string_key in export

**Comment by elo2112** [comment]
Would you mind rebasing one more time?  I just pushed another update to master.  If that one passes with your changes, it should be safe to accept the pull request.

**Comment by barmintor** [comment]
it failed, but I don't know *why*. Here's the export that was in the temp directory: https://gist.github.com/barmintor/aa445494adcee63998ad

**Comment by barmintor** [comment]
Oh, I see there was a change in the reversion I missed.

**Pull request merged**
